module.exports = {
  CHOOSE_ONE: 'chooseOne',
  MEETING_TIME: 'meetingTime',
  ERROR_POSITION_TYPE: 'ERROR_POSITION_TYPE',
  ERROR_POSITION_LATE: 'ERROR_POSITION_LATE',
  ERROR_POSITION_CHOICE: 'ERROR_POSITION_CHOICE',
  SCHEMA_VERSION: 'v1'
}
